### ISSUE TITLE
Rename to plugin-lua

### ISSUE THREAD

**Issue by suchipi** [prettier/plugin-lua#1]
@vjeux After transferring this repo to the prettier org, I no longer have access to its "Settings" tab, so I can't rename it to plugin-lua to match the other repos. Could you either rename it for me or give me access (if you know how)? Also could you verify @SpiralP and I both still have write access to the repo?

Sorry to bother you 😅

**Comment by vjeux** [comment]
Okay, you should both be admins :)

**Comment by suchipi** [comment]
Thank you!
